// shiny-badge/index.tsx
'use client'

import type { JSX } from 'react'

import type { NucShinyBadgeInterface } from 'nucleify'
import { AdIcon, t } from 'nucleify'

import './_index.scss'

export function NucShinyBadge({
  icon,
  label,
}: NucShinyBadgeInterface): JSX.Element {
  return (
    <span className="nuc-shiny-badge">
      <AdIcon icon={icon} className="iconify" />
      <span>{t(String(label ?? ''))}</span>
    </span>
  )
}

// components/shiny-badge/index.vue
<template>
  <span class="nuc-shiny-badge">
    <Icon :name="icon" />
    <span>{{ displayLabel }}</span>
  </span>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'

import type { NucShinyBadgeInterface } from './types'

const props = defineProps<NucShinyBadgeInterface>()
const { t, te } = useI18n()

const displayLabel = computed(() => {
  const raw = props.label != null ? String(props.label) : ''
  if (!raw.trim()) return ''
  return te(raw) ? t(raw) : raw
})
</script>
