// trust-badges/index.tsx
'use client'

import type { JSX } from 'react'

import { AdIcon, t } from 'nucleify'

import './_index.scss'

import type { NucTrustBadgeItemInterface } from 'nucleify'

export function NucTrustBadges({
  items,
}: {
  items?: NucTrustBadgeItemInterface[]
}): JSX.Element {
  return (
    <div className="nuc-trust-badges">
      {items?.map((item, index) => (
        <div
          key={`${item.icon}-${item.label}-${index}`}
          className="nuc-trust-badge-item"
        >
          <AdIcon icon={item.icon} className="iconify" />
          <span>{t(String(item.label ?? ''))}</span>
        </div>
      ))}
    </div>
  )
}

// components/trust-badges/index.vue
<template>
  <div class="nuc-trust-badges">
    <div v-for="item in items" :key="item.label" class="nuc-trust-badge-item">
      <Icon :name="item.icon" />
      <span>{{ $t(item.label, item.label) }}</span>
    </div>
  </div>
</template>

<script setup lang="ts">
import type { NucTrustBadgeItemInterface } from './types'

interface TrustBadgePropsInterface {
  items?: NucTrustBadgeItemInterface[]
}

defineProps<TrustBadgePropsInterface>()
</script>
