// home-link/index.tsx
'use client'

import type { JSX } from 'react'

import { AdAnchor } from 'nucleify'

import './_index.scss'

export function NucHomeLink(): JSX.Element {
  return (
    <AdAnchor
      href="/home"
      className="nuc-home-link"
      icon="prime:chevron-left"
      title="Back to home"
    />
  )
}

// components/home-link/index.vue
<template>
  <ad-anchor
    :href="`/${lang}/home`"
    class="nuc-home-link"
    icon="prime:chevron-left"
    title="Back to home"
  />
</template>

<script setup lang="ts">
import { useRoute } from 'nuxt/app'
import { computed } from 'vue'

const route = useRoute()
const lang = computed(() => (route.params.lang as string) || 'en')
</script>
