// submit-button/index.tsx
import type { JSX, MouseEvent } from 'react'

import type { ButtonInterface } from 'nucleify'
import { AdButton } from 'nucleify'

import './_index.scss'

export function NucSubmitButton({
  label,
  icon,
  className,
  onClick,
  variant,
  type = 'button',
  disabled = false,
}: ButtonInterface): JSX.Element {
  const rootClass = [
    'nuc-submit-button',
    variant && `nuc-submit-button-${variant}`,
    className,
  ]
    .filter(Boolean)
    .join(' ')

  return (
    <AdButton
      label={label}
      icon={icon}
      className={rootClass}
      nuiType={variant === 'primary' ? 'main' : undefined}
      type={type}
      disabled={disabled}
      onClick={onClick}
      gap={icon ? '0.5rem' : undefined}
    />
  )
}

// submit-button/index.vue
<template>
  <ad-button
    :class="[
      'nuc-submit-button',
      props.variant && `nuc-submit-button-${props.variant}`,
      props.class,
    ]"
    :icon="props.icon"
    :disabled="props.disabled"
    :type="props.type"
    @click="handleClick"
  >
    <strong>{{ props.label }}</strong>
  </ad-button>
</template>

<script setup lang="ts">
import type { ButtonInterface } from 'nucleify'

const props = defineProps<ButtonInterface>()

const emit = defineEmits<{
  click: [event: MouseEvent]
}>()

function handleClick(event: MouseEvent): void {
  emit('click', event)
}
</script>

<style lang="scss">
@import 'index';
</style>
