// tiles/index.tsx
'use client'

import type { JSX } from 'react'

import type { NucTilesInterface } from 'nucleify'
import { AdTile } from 'nucleify'

import './_index.scss'

export function NucTiles({ entities }: NucTilesInterface): JSX.Element {
  return (
    <div className="nuc-tiles">
      {entities.map((entity, index) => (
        <AdTile key={index} {...entity} />
      ))}
    </div>
  )
}

// tiles/index.vue
<template>
  <div class="nuc-tiles">
    <ad-tile
      v-for="(entity, index) in props.entities"
      v-bind="entity"
      :key="index"
    />
  </div>
</template>

<script setup lang="ts">
import type { NucTilesInterface } from 'nucleify'

const props = defineProps<NucTilesInterface>()
</script>

<style lang="scss">
@import 'index';
</style>
