// authors/index.tsx
import type { JSX } from 'react'

import { AdAnchor, AdDeferredContent, AdImage } from 'nucleify'

import './_index.scss'

export function NucAuthors(): JSX.Element {
  return (
    <AdAnchor
      href="https://github.com/Atomic-IT"
      className="template-authors"
      rel="noreferrer"
      target="_blank"
    >
      made by Atomic IT
      <AdDeferredContent>
        <AdImage
          src="/img/atomic-logo.webp"
          width="28"
          height="28"
          alt="Atomic IT logo"
          loading="lazy"
        />
      </AdDeferredContent>
    </AdAnchor>
  )
}

// components/authors/index.vue
<template>
  <ad-anchor href="https://github.com/Atomic-IT" class="template-authors">
    made by Atomic IT
    <deferred-content>
      <img
        :src="imgUrl + 'atomic-logo.webp'"
        width="28"
        height="28"
        alt="Atomic IT logo"
      />
    </deferred-content>
  </ad-anchor>
</template>
